In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.__version__

'2.0.1'

In [4]:
pip install --upgrade -- opencv-python

Note: you may need to restart the kernel to use updated packages.


In [5]:
pip install --upgrade numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import cv2

In [21]:
img =cv2.imread("C:\\Users\\aedpu\\OneDrive\\Pictures\\download (1).jpeg")

In [8]:
print(img)

[[[32 30 36]
  [32 30 36]
  [32 30 36]
  ...
  [18 17 19]
  [18 17 19]
  [18 17 19]]

 [[32 30 36]
  [32 30 36]
  [32 30 36]
  ...
  [18 17 19]
  [18 17 19]
  [18 17 19]]

 [[32 30 36]
  [32 30 36]
  [32 30 36]
  ...
  [18 17 19]
  [18 17 19]
  [18 17 19]]

 ...

 [[ 0  0  0]
  [ 0  0  0]
  [ 1  1  1]
  ...
  [ 0  0  0]
  [22 22 22]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 8  8  8]
  [ 9  9  9]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 8  8  8]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]


In [ ]:
cv2.imshow("captain" ,img)
cv2.waitKey(0)
cv2.destroyAllwindows()

In [9]:
g =cv2.imread("C:\\Users\\aedpu\\OneDrive\\Pictures\\download (1).jpeg",0)

In [10]:
g

array([[32, 32, 32, ..., 18, 18, 18],
       [32, 32, 32, ..., 18, 18, 18],
       [32, 32, 32, ..., 18, 18, 18],
       ...,
       [ 0,  0,  1, ...,  0, 22,  0],
       [ 0,  8,  9, ...,  0,  0,  8],
       [ 0,  0,  0, ...,  0,  0,  0]], dtype=uint8)

In [11]:
cv2.imshow("captain" ,g)
cv2.waitKey(0)
cv2.destroyAllwindows()

AttributeError: module 'cv2' has no attribute 'destroyAllwindows'

In [12]:
cv2.imwrite('saveimage.png', img)

True

In [14]:
#color spacing

In [ ]:
#color spacing change

In [15]:
colors_avl=[i for i in dir(cv2) if i.startswith("COLOR_BGR")]

In [17]:
print(colors_avl)

['COLOR_BGR2BGR555', 'COLOR_BGR2BGR565', 'COLOR_BGR2BGRA', 'COLOR_BGR2GRAY', 'COLOR_BGR2HLS', 'COLOR_BGR2HLS_FULL', 'COLOR_BGR2HSV', 'COLOR_BGR2HSV_FULL', 'COLOR_BGR2LAB', 'COLOR_BGR2LUV', 'COLOR_BGR2Lab', 'COLOR_BGR2Luv', 'COLOR_BGR2RGB', 'COLOR_BGR2RGBA', 'COLOR_BGR2XYZ', 'COLOR_BGR2YCR_CB', 'COLOR_BGR2YCrCb', 'COLOR_BGR2YUV', 'COLOR_BGR2YUV_I420', 'COLOR_BGR2YUV_IYUV', 'COLOR_BGR2YUV_UYNV', 'COLOR_BGR2YUV_UYVY', 'COLOR_BGR2YUV_Y422', 'COLOR_BGR2YUV_YUNV', 'COLOR_BGR2YUV_YUY2', 'COLOR_BGR2YUV_YUYV', 'COLOR_BGR2YUV_YV12', 'COLOR_BGR2YUV_YVYU', 'COLOR_BGR5552BGR', 'COLOR_BGR5552BGRA', 'COLOR_BGR5552GRAY', 'COLOR_BGR5552RGB', 'COLOR_BGR5552RGBA', 'COLOR_BGR5652BGR', 'COLOR_BGR5652BGRA', 'COLOR_BGR5652GRAY', 'COLOR_BGR5652RGB', 'COLOR_BGR5652RGBA', 'COLOR_BGRA2BGR', 'COLOR_BGRA2BGR555', 'COLOR_BGRA2BGR565', 'COLOR_BGRA2GRAY', 'COLOR_BGRA2RGB', 'COLOR_BGRA2RGBA', 'COLOR_BGRA2YUV_I420', 'COLOR_BGRA2YUV_IYUV', 'COLOR_BGRA2YUV_UYNV', 'COLOR_BGRA2YUV_UYVY', 'COLOR_BGRA2YUV_Y422', 'COLOR_BGRA2

In [18]:
print(len(colors_avl))

54


In [24]:
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
hsv =cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
rgb =cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

In [ ]:
cv2.imshow("gray",gray)
cv2.imshow("hsv",hsv)
cv2.imshow("original",img)
cv2.imshow("rgb",rgb)
cv2.waitKey(0)
cv2.destroyAllwindows()